chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='super_admin'),
    path('<str:room_name>/', views.room, name='room'),
    
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='super_admin'),
    path('', include('mainapp.urls')),
    path('students/', include('students.urls')),
    path('reportcards/', include('reportcards.urls')),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

students/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.students, name='students' ),
    path('register/', views.add, name='register_student'),
    path('import/', views.import_students, name='import_students'),
    path('details/<pk>/', views.student, name='student'),
    path('delete/<pk>/', views.delete_student, name='delete_student'),

    path('house/<hs>/', views.view_by_house, name='students_by_house'),
    path('<cl>/', views.view_by_class, name='students_by_class'),
    path('<cl>/<strm>/', views.view_by_stream, name='students_by_stream'),
]

students/models.py
import datetime
from django.db import models
# from mainapp.helper import allocate_house


class Subject(models.Model):
    name = models.CharField(max_length=100)
    abbr = models.CharField(max_length=6)
    alevel = models.BooleanField(default= False)
    olevel = models.BooleanField(default= False)
    olevel_code = models.CharField(max_length=10, blank=True, null=True)
    alevel_code = models.CharField(max_length=10, blank=True, null=True)
    is_compulsary = models.BooleanField(default=False)

    @property
    def olevel_papers(self):
        return Paper.objects.filter(subject = self, level = 'Olevel')

    @property
    def alevel_papers(self):
        return Paper.objects.filter(subject = self, level = 'Alevel')

    def __str__(self):
        return self.name

class Paper(models.Model):
    level_choices = (
        ('Alevel', 'Alevel'),
        ('Olevel', 'Olevel')
    )
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    level = models.CharField(max_length= 10, choices= level_choices)

    def __str__(self):
        return f'{self.subject} {self.name}'

class Student(models.Model):
    class_choices = (
        ('S.1', 'S.1'),
        ('S.2', 'S.2'),
        ('S.3', 'S.3'),
        ('S.4', 'S.4'),
        ('S.5', 'S.5'),
        ('S.6', 'S.6'),
    )

    streams = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('S', 'S'),
    )

    sex_choices = (
        ('Female', 'Female'),
        ('Male', 'Male')
    )

    house_choices = (
        ('Australia', 'Australia'),
        ('Brazil', 'Brazil'),
        ('Canada', 'Canada'),
        ('France', 'France'),
        ('Japan', 'Japan'),
        ('Nigeria', 'Nigeria')
    )

    sir_name = models.CharField(max_length=50)
    given_name = models.CharField(max_length=50)
    other_names = models.CharField(max_length=50, null=True, blank=True)
    sex = models.CharField(max_length=8, choices=sex_choices)
    passport_photo = models.ImageField(upload_to='passports', blank=True, null=True)
    klass = models.CharField(max_length=5, choices=class_choices)
    stream = models.CharField(max_length=10, choices=streams)
    house = models.CharField(max_length=10, choices=house_choices, blank=True, null=True)
    # subjects = models.ManyToManField(Subject, default= Subject.objects.filter(is_compulsary=True))
    date_added = models.DateTimeField(auto_now=True)
    scores = {}

    def __str__(self):
        return self.sir_name

    @property
    def full_names(self):
        if self.other_names != None:
            return f'{self.sir_name} {self.given_name} {self.other_names}'

        else:
            return f'{self.sir_name} {self.given_name}'

    @property
    def subjects(self):
        alevel_classes = ['S.5', 'S.6']
        if self.klass in alevel_classes:
            return Subject.objects.filter(alevel = True)
        else:
            return Subject.objects.filter(olevel = True)

        

students/views.py
import pandas
import numpy

from django.shortcuts import render, redirect
from mainapp import forms
from .models import Student, Subject
from mainapp.helper import allocate_house

def add(request):
    subjects = Subject.objects.all()
    form = forms.StudentRegistraionForm()

    if request.method == 'POST':
        if request.FILES.get('std_file'):
            return redirect('students')

        form = forms.StudentRegistraionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            '''
                Each time we create a student we need to check if this student's class stream has any marklist
                If so, then a result should be appended to the marklist for this student. 
            '''
            return redirect('register_student')

    context = {
        'form': form,
        'subjects': subjects,
    }
    return render(request, 'students/add.html', context)

def import_students(request):

    if request.method == 'POST':
        std_file = request.FILES['std_file']

        df = pandas.read_excel(std_file)
        df.fillna('')
        rows = len(df)
        print(df)

        i = 0
        while i < rows:
            df['Other Names'].fillna('', inplace=True)
            df['Sex'].fillna('', inplace=True)
            print(df['Other Names'][i])
            Student.objects.create(
                sir_name = df['Sir Name'][i],
                given_name = df['Given Name'][i],
                other_names = df['Other Names'][i],
                sex = df['Sex'][i],
                klass = df['Class'][i],
                stream = df['Stream'][i],
                house = allocate_house()
            )

            i += 1

    context = {}
    return render(request, 'students/import.html', context)

def students(request):
    students = Student.objects.all()
    context = {
        'students': students,
    }
    return render(request, 'students/students.html', context)

def student(request, pk):
    student = Student.objects.get(id=pk)
    form = forms.StudentRegistraionForm(instance=student)

    if request.method == 'POST':
        form = forms.StudentRegistraionForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('students')

    context = {
        'form': form,
        'student': student,
    }
    return render(request, 'students/student.html', context)

def delete_student(request, pk):
    student = Student.objects.get(id = pk)

    if request.method == 'POST':
        student.delete()
        return redirect('students')

    context ={
        'instance': student,
        'object': 'Student'
    }
    return render(request, 'mainapp/delete.html', context)

def view_by_class(request, cl):
    students = Student.objects.filter(klass = cl)

    context = {
        'students': students,
        'class': cl,
    }
    return render(request, 'students/view_by_class.html', context)

def view_by_stream(request, cl, strm):
    students = Student.objects.filter(klass = cl, stream = strm)

    context = {
        'students': students,
        'class': cl,
        'stream': strm,
    }
    return render(request, 'students/view_by_stream.html', context)

def view_by_house(request, hs):
    students = Student.objects.filter(house = hs)

    context = {
        'students': students,
        'hs': hs,
    }
    return render(request, 'students/view_by_house.html', context)

students/templates/students/add.html
{% extends 'mainapp/home.html' %}
{% load static %}
{% block page %}
    <div class="pt-5 pb-5 container">
        <div class="wrapper">
            <legend class="text-info text-center">Student Registration Form</legend>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_sir_name">{{ form.sir_name.label }}:</label>
                                {{ form.sir_name }}
                            </div>
                            <div class="form-group">
                                <label for="id_given_name">{{ form.given_name.label }}:</label>
                                {{ form.given_name }}
                            </div>
                            <div class="form-group">
                                <label for="id_other_names">{{ form.other_names.label }}:</label>
                                {{ form.other_names }}
                            </div>
                            <div class="form-group">
                                <label for="id_house">{{ form.house.label }}:</label>
                                {{ form.house }}
                            </div>
                            <div class="form-group">
                                <label for="id_passport_photo">{{ form.passport_photo.label }}:</label>
                                {{ form.passport_photo }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="id_sex">{{ form.sex.label }}:</label>
                                {{ form.sex }}
                            </div>
                            <div class="form-group">
                                <label for="id_klass">Class:</label>
                                {{ form.klass }}
                            </div>
                            <div class="form-group">
                                <label for="id_stream">{{ form.stream.label }}:</label>
                                {{ form.stream }}
                            </div>
                            <div class="form-group">
                                <label for="id_subjects">{{ form.subjects.label }}:</label>
                                {{ form.subjects }}
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-group" style="margin: auto;">
                    <button type="submit" class="btn btn-outline-success">Register</button>
                </div>
            </form>
        </div>
    </div>

{% endblock page %}
{% block javascript %}
    <script>

        setName('input');
        setName('select')
        
        function setName(elem) {
            arr = document.getElementsByTagName(elem);
            for (let i = 0; i < arr.length; i++) {
                const element = arr[i];
                if(element.type !== 'submit'){
                    element.className = 'form-control';
                }
            }
        }
    </script>
{% endblock javascript %}

students/templates/students/import.html
{% extends 'mainapp/home.html' %}

{% block style %}
    <style>
        
    </style>
{% endblock style %}
{% block page %}
    <div class="container">
        <div class="wrapper mt-5">
            <div class="ml-5">
                <h4 class="text-warning ml-5"><b>NOTE:</b></h4>
                <div class="jumbotron ml-5 mr-5">
                    <p class="ml-5">1. Your file <b>MUST</b> be an excel file ie: it should be a ".xlsx" or ".xls" file</p>
                    <p class="ml-5">2. The <b>KEY</b> fields are: "sir_name", "given_name", "sex", "class", "stream"</p>
                    <p class="ml-5">3. Your file <b>MUST</b> have all the five key columns or compulsary fields named as exactly as indicated here.</p>
                </div><hr>
                <form action="" method="POST" id="import_form" enctype="multipart/form-data" class="text-center">
                    {% csrf_token %}
                    <fieldset>
                        <div class="text-center">
                            <div class="form-group">
                                <label for="std_file" class="text-primary">Choose your <b class="text-danger">EXCEL</b> file</label><br>
                                <input type="file" style="width: 300px; margin: auto;" name="std_file" id="std_file" required class="form-control">
                            </div>
                        </div>
                    </fieldset>
                    <button type="submit" class="btn btn-outline-success">Import Students</button>
                </form>
            </div>
        </div>
    </div>
{% endblock page %}

{% block javascript %}
    <script>
        
    </script>
{% endblock javascript %}

students/templates/students/student.html
{% extends 'mainapp/home.html' %}
{% block page %}
    <div class="container pt-5 pb-5">
        <div class="wrapper col-md-10">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center text-info">{{ student.full_names }}'s Basic Data</h2>
                </div>
                <div class="card-body">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_sir_name">{{ form.sir_name.label }}:</label>
                                        {{ form.sir_name }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_given_name">{{ form.given_name.label }}:</label>
                                        {{ form.given_name }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_other_names">{{ form.other_names.label }}:</label>
                                        {{ form.other_names }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_house">{{ form.house.label }}:</label>
                                        {{ form.house }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_passport_photo">{{ form.passport_photo.label }}:</label>
                                        {{ form.passport_photo }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_sex">{{ form.sex.label }}:</label>
                                        {{ form.sex }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_klass">Class:</label>
                                        {{ form.klass }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_stream">{{ form.stream.label }}:</label>
                                        {{ form.stream }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_subjects">{{ form.subjects.label }}:</label>
                                        {{ form.subjects }}
                                    </div>
                                </div>
                            </div>
                        </fieldset><hr>
                        <div class="form-group">
                            <div class="h-gird-3">
                                <a href="{% url 'students' %}" class="btn btn-outline-info">
                                    Cancel
                                </a>
                                <button type="submit" class="btn btn-outline-success">
                                    Save Changes
                                </button>
                                <a href="{% url 'delete_student' student.id %}" class="btn btn-outline-danger">
                                    Delete Student
                                </a>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock page %}

{% block javascript %}
<!-- the script to add a class to inputs and or selects -->
    <script>
        setName('input');
        setName('select')
        
        function setName(elem) {
            arr = document.getElementsByTagName(elem);
            for (let i = 0; i < arr.length; i++) {
                const element = arr[i];
                // if the input type is text or password
                if(element.type !== 'checkbox'){
                    element.className = 'form-control';
                }
            }
        }
    </script>
{% endblock javascript %}

students/templates/students/students.html
{% extends 'mainapp/home.html' %}
{% block style %}
<style>
</style>
{% endblock style %}
{% block page %}
    <h2 class="text-center text-info">All Students Registered</h2><hr>
    <div class="row">
        <div class="col-md-4">
            <div class="sider">
                <h4 class="text-center text-info">Sort Students</h4>
                <hr>
                    <div class="h-gird-3">
                        <label for="class" class="text-right">By Class:</label>
                        <select id="class">
                            <option value="S.1">S.1</option>
                            <option value="S.2">S.2</option>
                            <option value="S.3">S.3</option>
                            <option value="S.4">S.4</option>
                            <option value="S.5">S.5</option>
                            <option value="S.6">S.6</option>
                        </select>
                    </div>
                    <hr>
                    <div class="h-gird-3">
                        <label for="class" class="text-right">By Stream:</label>
                        <select id="class">
                            <option value="S.1">S.1</option>
                            <option value="S.2">S.2</option>
                            <option value="S.3">S.3</option>
                            <option value="S.4">S.4</option>
                            <option value="S.5">S.5</option>
                            <option value="S.6">S.6</option>
                        </select>
                    </div>
                    <hr>
                    <div class="h-gird-3">
                        <label for="class" class="text-right">By House:</label>
                        <select id="class">
                            <option value="S.1">S.1</option>
                            <option value="S.2">S.2</option>
                            <option value="S.3">S.3</option>
                            <option value="S.4">S.4</option>
                            <option value="S.5">S.5</option>
                            <option value="S.6">S.6</option>
                        </select>
                    </div>
                <hr>
                <a href="{% url 'register_student' %}" class="btn btn-outline-success">Register new students</a>
            </div>
        </div>
        <div class="col-md-8">
            <table class="table table-bordered table-striped">
                <thead>
                    <th>Student Names</th>
                    <th>Sex</th>
                    <th>Class</th>
                    <th>Stream</th>
                    <th>House</th>
                </thead>
                <tbody>
                    {% for s in students %}
                        <tr>
                            <td><a href="{% url 'student' s.id %}">{{s.full_names}}</a></td>
                            <td>{{s.sex}}</td>
                            <td><a href="{% url 'students_by_class' s.klass %}">{{s.klass}}</a></td>
                            <td><a href="{% url 'students_by_stream' s.klass s.stream %}">{{s.stream}}</a></td>
                            <td><a href="{% url 'students_by_house' s.house %}">{{s.house}}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock page %}

students/templates/students/view_by_class.html
{% extends 'mainapp/home.html' %}
{% block style %}
<style>
</style>
{% endblock style %}
{% block page %}
    <div class="container">
        <h5 class="text-center text-info">Students In {{ class }}</h5><hr>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Student Names</th>
                    <th>Sex</th>
                    <th>Stream</th>
                    <th>House</th>
                </tr>
            </thead>
            <tbody>
                {% for s in students %}
                    <tr>
                        <td><a href="{% url 'student' s.id %}">{{s.full_names}}</a></td>
                        <td>{{s.sex}}</td>
                        <td><a href="{% url 'students_by_stream' s.klass s.stream %}">{{s.stream}}</a></td>
                        <td><a href="{% url 'students_by_house' s.house %}">{{s.house}}</a> </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock page %}

students/templates/students/view_by_house.html
{% extends 'mainapp/home.html' %}
{% block style %}
<style>
</style>
{% endblock style %}
{% block page %}
    <div class="container">
        <h5 class="text-center text-info">students In {{ hs }}</h5>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Student Names</th>
                    <th>Sex</th>
                    <th>Stream</th>
                    <th>House</th>
                </tr>
            </thead>
            <tbody>
                {% for s in students %}
                    <tr>
                        <td><a href="{% url 'student' s.id %}">{{s.full_names}}</a></td>
                        <td>{{s.sex}}</td>
                        <td><a href="{% url 'students_by_class' s.klass %}">{{s.klass}}</a></td>
                        <td><a href="{% url 'students_by_stream' s.klass s.stream %}">{{s.stream}}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock page %}

students/templates/students/view_by_stream.html
{% extends 'mainapp/home.html' %}
{% block style %}
<style>
</style>
{% endblock style %}
{% block page %}
    <div class="container">
        <h5 class="text-center text-info">Students In {{ class }} {{ stream }}</h5><hr>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Student Names</th>
                    <th>Sex</th>
                    <th>House</th>
                </tr>
            </thead>
            <tbody>
                {% for s in students %}
                    <tr>
                        <td><a href="{% url 'student' s.id %}">{{s.full_names}}</a></td>
                        <td>{{s.sex}}</td>
                        <td><a href="{% url 'students_by_house' s.house %}">{{s.house}}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock page %}